### ISSUE TITLE
Automatically Add Token To All API Requests

### ISSUE THREAD

**Issue by troy-johnson** [troy-johnson/team-manager-app#13]
Currently, adding an API call to a component consists of adding the call to src/api/UserService.js (or similar) like this:

```
export const test = async (params, token) => {
  const response = await fetch('https://jsonplaceholder.typicode.com/todos/1', {
    method: 'GET',
    headers: {
      Authorization: `Bearer ${token}`
    }
  });

  return await response.json();
}
```
The token is passed in from the useApi hook, but this requires that you manually add the Authorization header in every API call. 

Figure out a way to automatically add the Authorization header to every API call (using a hook or other solution). Note that obtaining the token requires usage of the useAuth0 hook, so a fetch/axios wrapper may be the easiest solution.

**Comment by bnelso23** [comment]
I accidently pushed this to master instead of the branch I made... oops...
